FROM amazoncorretto:21-alpine

WORKDIR /app

ENV PROFILES=prod

ARG ORIGINAL_JAR_FILE=./build/libs/backend-SNAPSHOT.jar

COPY ${ORIGINAL_JAR_FILE} builzer-backend.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/builzer-backend.jar"]