spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: backend
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: false

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ap-northeast-2
  route53:
    hostedZoneId: ${AWS_ROUTE53_HOSTED_ZONE_ID}